name: Lint, build and test

on: [push, pull_request]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      #fail-fast: false
      matrix:
        nodejs: ["22", "24"]

    steps:
    - uses: actions/checkout@v2

    # https://github.com/actions/setup-node
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.nodejs }}

    - run: npm ci
    - run: npm run build
    - run: npm test
    - run: npm run lint
